### PR TITLE
Test displaying the resume text #48  Changes made by Aaryamantriescode are:

### PR DESCRIPTION
**Pull request by aaryamantriescode**
Add tests #25
 Dynamic menu now shows "Edit resume" if resume exists.
 Added tests for managing and displaying resumes.
 Improved resume management and display functionality in the code.

### CODE REVIEW

**Comment by aaryamantriescode** [comment]
hi @nicobrenner I have tried my best and made something work I think😊. Go through the changes and let me know if anything was wrong !

**Comment by nicobrenner** [comment]
Hi @aaryamantriescode thank you so much for creating this PR in response to the issue #48

I will now review the changes proposed in the PR and make comments about the changes

This is pretty normal and typical of reviewing code and managing a shared codebase

I will do my best to provide you with proper and useful feedback in a friendly way

Thank you for your time, contributions and understanding

Looking forward to keep building Command Jobs with you


Nico

**Comment by nicobrenner** [comment]
Ok, @aaryamantriescode just finished reviewing the PR. I really like it overall. I think it's going in a really good direction and would definitely like to incorporate most of the changes

I made some comments about where docker-related files should go in the project, and also would like some clarification about the Visual Studio configuration files for docker

Besides that, there are some minors adjustments for the test file and it should be good to go

Thank you so much, I look forward to seeing this PR added to the codebase

**Comment by aaryamantriescode** [comment]
> Hi @aaryamantriescode thank you so much for creating this PR in response to the issue #48
> 
> I will now review the changes proposed in the PR and make comments about the changes
> 
> This is pretty normal and typical of reviewing code and managing a shared codebase
> 
> I will do my best to provide you with proper and useful feedback in a friendly way
> 
> Thank you for your time, contributions and understanding
> 
> Looking forward to keep building Command Jobs with you
> 
> Nico


Thanks! I would love to build more with you 🤞I am learning a lot and like the project😍

**Comment by aaryamantriescode** [comment]
> Ok, @aaryamantriescode just finished reviewing the PR. I really like it overall. I think it's going in a really good direction and would definitely like to incorporate most of the changes
> 
> I made some comments about where docker-related files should go in the project, and also would like some clarification about the Visual Studio configuration files for docker
> 
> Besides that, there are some minors adjustments for the test file and it should be good to go
> 
> Thank you so much, I look forward to seeing this PR added to the codebase

Oh i didnt realize that VS code docker file was commited to the code I it reccomended me to download it and I thought it would be for my personal computer . can you help me out by explaining which files I need to change?

**Comment by nicobrenner** [comment]
> > Ok, @aaryamantriescode just finished reviewing the PR. I really like it overall. I think it's going in a really good direction and would definitely like to incorporate most of the changes
> > I made some comments about where docker-related files should go in the project, and also would like some clarification about the Visual Studio configuration files for docker
> > Besides that, there are some minors adjustments for the test file and it should be good to go
> > Thank you so much, I look forward to seeing this PR added to the codebase
> 
> Oh i didnt realize that VS code docker file was commited to the code , It reccomended me to download it and I thought it would be for my personal computer . can you help me out by explaining which files I need to change?

Looking into it, keep the `.vscode` folder with the two `.json` files, but move all the docker-related files to the `docker/` folder. Then adjust the `.json` files within `.vscode` to make sure they reference the docker files in `docker/`. There should be no docker-related files in the root of the repo

**Comment by aaryamantriescode** [comment]
> > > Ok, @aaryamantriescode just finished reviewing the PR. I really like it overall. I think it's going in a really good direction and would definitely like to incorporate most of the changes
> > > I made some comments about where docker-related files should go in the project, and also would like some clarification about the Visual Studio configuration files for docker
> > > Besides that, there are some minors adjustments for the test file and it should be good to go
> > > Thank you so much, I look forward to seeing this PR added to the codebase
> > 
> > 
> > Oh i didnt realize that VS code docker file was commited to the code , It reccomended me to download it and I thought it would be for my personal computer . can you help me out by explaining which files I need to change?
> 
> Looking into it, keep the `.vscode` folder with the two `.json` files, but move all the docker-related files to the `docker/` folder. Then adjust the `.json` files within `.vscode` to make sure they reference the docker files in `docker/`. There should be no docker-related files in the root of the repo

I am not so sure why its telling me i deleted some files but everything should be in the correct files

**Comment by nicobrenner** [comment]
Thank you @aaryamantriescode, I see you moved the Docker-related files to the `docker/` folder, that's great

Now please:

* make sure that the commands for building and running the app still work correctly with the new docker files (I just tried them and had to make some changes to get them working, also the docker-compose file needs some tweaking, it needs the tty and stdin_open lines as well as this volume - ../:/commandjobs)
* remove the `.vscode` folder, and add and entry for it in `.gitignore`
* remove the `requirements.txt` file in the root of the repo

**Comment by aaryamantriescode** [comment]
> Thank you @aaryamantriescode, I see you moved the Docker-related files to the `docker/` folder, that's great
> 
> Now please:
> 
> * make sure that the commands for building and running the app still work correctly with the new docker files (I just tried them and had to make some changes to get them working, also the docker-compose file needs some tweaking, it needs the tty and stdin_open lines as well as this volume - ../:/commandjobs)
> * remove the `.vscode` folder, and add and entry for it in `.gitignore`
> * remove the `requirements.txt` file in the root of the repo
Hi, I have a question. How can I just go back to the original code where I didn't mess up the files, so I can make the changes only to the menu and test menu file.

**Comment by nicobrenner** [comment]
> Hi, I have a question. How can I just go back to the original code where I didn't mess up the files, so I can make the changes only to the menu and test menu file

It's all good, you didn't mess anything up, playing with code is how we learn how things work

Having said that, it might be faster to get a clean PR by starting from the current master branch of commanjobs

Probably the easiest way to do that, is to just git clone the repo (`git clone git@github.com:nicobrenner/commandjobs.git`)   in a different folder, that way you'll get the code exactly as it is now in master

There you can add the changes you want

**Comment by aaryamantriescode** [comment]
image_2024-03-18_080449331
 yeah, I am so lost🥲

**Comment by nicobrenner** [comment]
Not sure what's going on, I think I had a similar issue the other day. Just tried it in my local and it worked though:

```sh
git clone git@github.com:nicobrenner/commandjobs.git commandjobs_new
```

image

**Comment by aaryamantriescode** [comment]
Yeah, it still isn't working for me, I think the best option could be to revert all the commits and start over again.

**Pull request closed without merging**
